### PR TITLE
iojs and nodejs use dedicated url attribute

### LINKED ISSUE #85: Setting the nodejs engine to iojs and install_method to 'source' does not change the prefix_url
Hello,

I'm new to chef.. and I don't open many bugs bare with me....

my /cookbook/attributes/default.rb
default['nodejs']['engine'] = 'iojs'
default['nodejs']['version'] = '2.2.1'
default['nodejs']['source'] = { :checksum => '55e79cc4f4cde41f03c1e204d2af5ee4b6e4edcf14defc82e518436e939195fa' }
default['nodejs']['install_method'] = 'source'

Keeps creating this chef error:
```  ================================================================================
  Error executing action `create` on resource 'remote_file[/var/chef/cache/iojs-source-2.2.1.tar.gz]'
  ================================================================================

Net::HTTPServerException
  ------------------------
  404 "Not Found"
  
  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/ark/providers/default.rb
  
  279:   remote_file new_resource.release_file do
  280:     Chef::Log.debug('DEBUG: new_resource.release_file')
  281:     source new_resource.url
  282:     checksum new_resource.checksum if new_resource.checksum
  283:     action :create
  284:     notifies :run, "execute[unpack #{new_resource.release_file}]"
  285:   end
  286: 
  
  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/ark/providers/default.rb:279:in `block in class_from_file'
  
  remote_file("/var/chef/cache/iojs-source-2.2.1.tar.gz") do
    provider Chef::Provider::RemoteFile
    action [:create]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    path "/var/chef/cache/iojs-source-2.2.1.tar.gz"
    backup 5
    atomic_update true
    source ["http://nodejs.org/dist/v2.2.1/iojs-v2.2.1.tar.gz"]
    use_etag true
    use_last_modified true
    declared_type :remote_file
    cookbook_name "nodejs"
    checksum "55e79cc4f4cde41f03c1e204d2af5ee4b6e4edcf14defc82e518436e939195fa"
  end
  ``` 

Notice the source goes and fetch from the nodejs and not iojs server

If I override the prefix_url in my cookbook before load the include_recipe of "nodejs" with
node.override['nodejs']['prefix_url'] = 'http://iojs.org/dist/'

Then it works fine.

So I'm wondering if the
https://github.com/redguide/nodejs/blob/8fde9f58856c1243551ab9c2492c96bb420698ed/attributes/default.rb#L31

Works as intended?

Thanks,
Kyle

### PR DESCRIPTION
**Pull request by BarthV**
Fixes #85

### CODE REVIEW

**Comment by mburns** [comment]
Since iojs is [merging back into](http://blog.nodejs.org/2015/05/15/the-nodejs-foundation-benefits-all/) node, I don't know that this change is actually useful. The default *should* be 'node' as that is the common case and at some point is likely to be the only case. Unless there is an attributes race condition issue or some other driving need for this change, I'd say -1.

**Comment by BarthV** [comment]
Ok,
so we would rather wait a bit, and remove all the work done to support multiple engine.
@guilhem : are you ok with that ?

**Comment by mburns** [comment]
I missed that this fixes a specific bug and jumped right to the code, so I spoke too soon.

After looking closer, there *is* in fact a sort-of race condition going on that this PR solves. The attributes are computed before it gets to the convergence step, so including `nodejs::iojs`, which sets the the `engine` attribute doesn't influence the `install_method` attribute because it has already been set. So, to correctly install iojs you need to set both `engine` && `version`.

Takeaways:
* we should improve test coverage, specifically for iojs source & package installs
* we should have a reasonable 'latest' iojs default version, like we have for node to simplify

:+1:, this now seems like a reasonable fix. Sorry for jumping the gun. :smile:

**Comment by BarthV** [comment]
thx for the review.

We're using many ```case node['nodejs']['engine']``` in attributes files, We should check if thoses tests are not impacted by this "sort-of-race" condition as well ...

no time for this atm

**Comment by guilhem** [comment]
:+1: for this quick fix
I really hope for iojs and nodejs to be merged soon :D

**Pull request merged**
