### PR TITLE
Add support for Mac OS X (using homebrew).

### PR DESCRIPTION
**Pull request by danieljimenez**

### CODE REVIEW

**Comment by danieljimenez** [comment]
Tested both via Kitchen (I have a custom Mac OS X VMWare Vagrant box) and on my test 2014 iMac with a fresh install.

**Comment by danieljimenez** [comment]
Any hope of merging this?

**Comment by guilhem** [comment]
can you squash it then re-ping me? :)

**Comment by danieljimenez** [comment]
@guilhem done!

**Comment by BarthV** [comment]
```Chef::Provider::Package::Homebrew``` uses ```homebrew_user``` attribute.
Should we port this attribute into  node install recipe ? (I don't think so)

:ok: btw

**Comment by danieljimenez** [comment]
@BarthV I'm new to Ruby and Chef, so I'll go with what you guys think. Right now this works on my boxes though and I wanted to get it upstream :).

**Comment by BarthV** [comment]
Don't worry :), it was more to provide some enlightenment for @guilhem.
In Redguide every PR must be reviewed and validated by 2 members.

**Comment by guilhem** [comment]
This PR is small enough to be merged "without any more guarantee" :)

**Comment by danieljimenez** [comment]
Should we up the version number too?

**Pull request merged**
