### PR TITLE
Testing / Readme updates

### PR DESCRIPTION
**Pull request by tas50**
Broken out into a change per commit

### CODE REVIEW

**Comment by tas50** [comment]
Looks like I'm going to have to resolve some failures before this is ready for a merge

**Comment by guilhem** [comment]
Many good ideas, hope to see this in a working version soon ;)

**Comment by tas50** [comment]
@guilhem I've removed inspec and I'm going to see what's going on with the remaining failures.

**Comment by tas50** [comment]
@guilhem If you restart the single job that failed it will probably complete.  That's just a job timing out and not an actual failure

**Comment by guilhem** [comment]
@tas50 didn't work even after a restart :/

**Comment by guilhem** [comment]
`./configure` take more than 10min without logout, _travis_ kill the job

**Comment by tas50** [comment]
I'm going to remove some of the testing stuff and submit a smaller PR here

**Pull request closed without merging**
